language: node_js
node_js:
  - 8
  - 10
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
sudo: false
dist: xenial
services:
  - xvfb
